name: Build Linux

on:
  workflow_call:

env:
  PROJECT_NAME: 'ParticleSystem'
  ZIP_NAME: 'linux-x64'

jobs:
  linux:
    runs-on: ubuntu-latest
    
    strategy:
        fail-fast: false
        matrix:
          build-configuration: [debug, release]
          build-platform: [x64] # TODO: remove

    steps:
    - name: Clone Git Repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./generate_project.sh

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: make config=${{matrix.build-configuration}}
